sudo: required
services: docker
before_install:
- sudo apt-get update
- sudo apt-get -o Dpkg::Options::="--force-confnew" install -y docker-engine
- openssl aes-256-cbc -K $encrypted_b96fd4fff813_key -iv $encrypted_b96fd4fff813_iv -in .private/data.tar.enc -out .private/data.tar -d
- tar xvf .private/data.tar -C .private
script: git fetch --unshallow --tags && ./dockerized-build && ./dockerized-deploy
branches:
  only:
    - master
notifications:
  slack:
    secure: UFJ/Ohpw3sOCIrsEQmTHCIOvWG3ISYUKefYuVC662Rgelon84690qVtEW+BXI51IQMLS1b4GiofofvoRZzGF6kzl4vI6FcNpf9wojP1sSL/VwvtrtFVwGZ502gVR0zh/nMeESLsNMfapPAdZ/IllSj4haLxQXQ9C3GpcYkjuj4zgmMllhC2jhWdDoG0jhlBse15b8gKgWMv6Hq5JKJHz85EDs9KWj91zGmC2J+1Yixo8ysTJeI18PlfcCIamfJKkkHRhL3gjc5KKFv0Dp6drxvUJtmrEvSwFgaP69WCQX9T/5nNkGu4kvVYY1pr3494xYMJX9YUg4uBbASygGAB+8HO6ESpU2/Ar3trd8AZHA2Pc9aqylXYR0MeXWyDWbM0zSQwhoCjW5rLxdvRBizr5s+hazGbSbjtJFTYJ35S5nuH5ga3qJfoh9p2PQQhIxR1TVr0NG067WHeJGvxUUW/F24dgiTgJjDeods9Fybeslk4U0UivL18fvubceA9ttm992S5G2PlW06VkUSv5amxw+56Nyq8C4x0PB/7m3eypFU97mEkzRUy2XK6EmgFWMtchOY42MVaYH3kmPdNLzwzjyVj+h2gMKZolp/JsgYWg7K6LAlrQU8v6+QreaIa8XdaVv3WWfdqnRGiyIuQ7hrNg+T7a/Q/D+7/QddeSvFi+luU=
