#!/bin/bash
set -e
source connectus-build-tools/utils/preconditions

APP_DIR=${APP_DIR:-$(pwd)}
PRIVATE_DIR=${PRIVATE_DIR:-$(pwd)/.private}

checkDockerVersion "1.10.3" "Only version 1.10.3 of Docker is supported"
checkDir "$APP_DIR" "APP_DIR must reference the app directory"
checkUrl "$CU_FIREBASE_URL" "CU_FIREBASE_URL must reference a valid Firebase app URL"
checkNotBlank "$CU_FIREBASE_JWT_TOKEN" "CU_FIREBASE_JWT_TOKEN must contain a token for accessing the Firebase database"
checkNotBlank "$SLACK_TOKEN" "SLACK_TOKEN must contain an access token for accessing Slack"

docker run                                                                                             \
    --rm                                                                                               \
    --volumes-from connectus-build-cache                                                               \
    -e ANDROID_RELEASE_KEYSTORE_PATH=/private/connectus-release.keystore                               \
    -e ANDROID_RELEASE_KEYSTORE_PASSWORD=secret                                                        \
    -e ANDROID_RELEASE_KEY_ALIAS=release                                                               \
    -e ANDROID_RELEASE_KEY_PASSWORD=secret                                                             \
    -e ANDROID_PLAY_PUBLISHER_SERVICE_ACCOUNT_JSON_PATH=/private/connectus-play-publisher-account.json \
    -e CU_FIREBASE_URL=$CU_FIREBASE_URL                                                                \
    -v $PRIVATE_DIR:/private                                                                           \
    -v $APP_DIR:/workspace                                                                             \
    -w /workspace/connectus-android-app                                                                \
    connectus-build                                                                                    \
    ./gradlew --no-daemon publishApkRelease
docker run                                          \
    --rm                                            \
    -e CU_FIREBASE_URL=$CU_FIREBASE_URL             \
    -e CU_FIREBASE_JWT_TOKEN=$CU_FIREBASE_JWT_TOKEN \
    -e SLACK_TOKEN=$SLACK_TOKEN                     \
    -v $PRIVATE_DIR:/private                        \
    -v $APP_DIR:/workspace                          \
    -w /workspace/connectus-android-app             \
    connectus-build                                 \
    /bin/bash -c "upload-release-description && upload-apk-to-slack"
docker run                                             \
    --rm                                               \
    -e HEROKU_SSH_KEY_PATH=/private/id_rsa-ci-4-heroku \
    -v $PRIVATE_DIR:/private                           \
    -v $APP_DIR:/workspace                             \
    -w /workspace/connectus-backend                    \
    connectus-build                                    \
    deploy-to-heroku
