#!/bin/bash
set -e

APP_DIR=${APP_DIR:-$(pwd)}
PRIVATE_DIR=${PRIVATE_DIR:-$(pwd)/.private}

docker run                                                                                             \
    --rm                                                                                               \
    --volumes-from connectus-build-cache                                                               \
    -e ANDROID_RELEASE_KEYSTORE_PATH=/private/connectus-release.keystore                               \
    -e ANDROID_RELEASE_KEYSTORE_PASSWORD=secret                                                        \
    -e ANDROID_RELEASE_KEY_ALIAS=release                                                               \
    -e ANDROID_RELEASE_KEY_PASSWORD=secret                                                             \
    -e ANDROID_PLAY_PUBLISHER_SERVICE_ACCOUNT_JSON_PATH=/private/connectus-play-publisher-account.json \
    -e APPLICATION_FIREBASE_URL=$APPLICATION_FIREBASE_URL                                              \
    -v $PRIVATE_DIR:/private                                                                           \
    -v $APP_DIR:/workspace                                                                             \
    -w /workspace/connectus-android-app                                                                \
    connectus-build                                                                                    \
    ./gradlew --no-daemon publishApkRelease
docker run                                                            \
    --rm                                                              \
    -e APPLICATION_FIREBASE_URL=$APPLICATION_FIREBASE_URL             \
    -e APPLICATION_FIREBASE_JWT_TOKEN=$APPLICATION_FIREBASE_JWT_TOKEN \
    -v $PRIVATE_DIR:/private                                          \
    -v $APP_DIR:/workspace                                            \
    -w /workspace/connectus-android-app                               \
    connectus-build                                                   \
    /bin/bash -c "upload-release-description && upload-apk-to-dropbox"
docker run                                             \
    --rm                                               \
    -e HEROKU_SSH_KEY_PATH=/private/id_rsa-ci-4-heroku \
    -v $PRIVATE_DIR:/private                           \
    -v $APP_DIR:/workspace                             \
    -w /workspace/connectus-backend                    \
    connectus-build                                    \
    deploy-to-heroku
