#!/bin/bash
set -e
docker build                           \
    --build-arg=USER_UID=$(id -u)      \
    --build-arg=USER_GID=$(id -g)      \
    -t connectus-build                 \
    connectus-build-tools/docker-build
docker build                      \
    --build-arg=USER_UID=$(id -u) \
    --build-arg=USER_GID=$(id -g) \
    -t connectus-build-cache      \
    connectus-build-tools/docker-build-cache
docker create                    \
    --name connectus-build-cache \
    connectus-build-cache || echo "Data container for build caches already exists, keep it for faster build executions."
docker run                               \
    -it --rm                             \
    --volumes-from connectus-build-cache \
    -v $(pwd):/workspace                 \
    -w /workspace/connectus-backend      \
    connectus-build                      \
    sbt stage
docker run                                                \
    -it --rm                                              \
    --volumes-from connectus-build-cache                  \
    -e APPLICATION_FIREBASE_URL=$APPLICATION_FIREBASE_URL \
    -v $(pwd):/workspace                                  \
    -w /workspace/connectus-android-app                   \
    connectus-build                                       \
    /bin/bash -c "init-emulator && ./gradlew connectedAndroidTest"
