#!/bin/bash
set -e

USER_UID=${USER_UID:-$(id -u)}
USER_GID=${USER_GID:-$(id -g)}
APP_DIR=${APP_DIR:-$(pwd)}

docker build                       \
    --build-arg=USER_UID=$USER_UID \
    --build-arg=USER_GID=$USER_GID \
    -t connectus-build             \
    connectus-build-tools/docker-build
docker build                       \
    --build-arg=USER_UID=$USER_UID \
    --build-arg=USER_GID=$USER_GID \
    -t connectus-build-cache       \
    connectus-build-tools/docker-build-cache
docker create                    \
    --name connectus-build-cache \
    connectus-build-cache || echo "Data container for build caches already exists, keep it for faster build executions."
docker run                               \
    --rm                                 \
    --volumes-from connectus-build-cache \
    -v $APP_DIR:/workspace               \
    -w /workspace/connectus-backend      \
    connectus-build                      \
    sbt test stage
docker run                               \
    --rm                                 \
    --volumes-from connectus-build-cache \
    -e CU_FIREBASE_URL=$CU_FIREBASE_URL  \
    -v $APP_DIR:/workspace               \
    -w /workspace/connectus-android-app  \
    connectus-build                      \
    /bin/bash -c "init-android-sdk && init-emulator ~/android-sdk-conf/samsung_galaxy_tab_a/arm.conf && ./gradlew --no-daemon test connectedAndroidTest"
