#!/bin/bash

set -e

function wait-for-lock-screen {
  echo "Waiting for the android operating system to initialize itself"
  while ! adb shell ps 2> /dev/null | grep com.android.music &> /dev/null
  do
    sleep 5
    echo "."
  done
  echo "The emulator is now fully initialized"
}

function unlock-screen {
  adb shell input tap 638 706
  adb shell input tap 191 226
  adb shell input keyevent KEYCODE_HOME
}

android create avd -n testavd -t 'Google Inc.:Google APIs:19'
cp /home/connectus/config.ini $ANDROID_SDK_HOME/.android/avd/testavd.avd/config.ini
emulator64-arm -avd testavd -no-skin -no-audio -no-window &
adb wait-for-device
wait-for-lock-screen
unlock-screen
